# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache {C:/Users/Christian Ulstrand/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-16668-DESKTOP-KRIG1B0/incrSyn}
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Christian Ulstrand/Documents/GitHub/3-Ugers-Projekt/3WeekProject/3WeekProject.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Christian Ulstrand/Documents/GitHub/3-Ugers-Projekt/3WeekProject/3WeekProject.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:2.0 [current_project]
set_property ip_output_repo {c:/Users/Christian Ulstrand/Documents/GitHub/3-Ugers-Projekt/3WeekProject/3WeekProject.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/Christian Ulstrand/OneDrive/DTU - IT Elektronik/2. Semester/Digitale Systemer/Software/3 ugers/LC3/LC3Zybo/BtnToggle.vhd}
  {C:/Users/Christian Ulstrand/Documents/GitHub/3-Ugers-Projekt/3WeekProject/3WeekProject.srcs/sources_1/new/Memory.vhd}
  {C:/Users/Christian Ulstrand/OneDrive/DTU - IT Elektronik/2. Semester/Digitale Systemer/Software/3 ugers/LC3/LC3Zybo/debounce.vhd}
  {C:/Users/Christian Ulstrand/Downloads/LC3Zybo/lc3_wrapper_multiplexers.vhd}
  {C:/Users/Christian Ulstrand/OneDrive/DTU - IT Elektronik/2. Semester/Digitale Systemer/Software/3 ugers/LC3/LC3Zybo/lc3_wrapper_multiplexers.vhd}
  {C:/Users/Christian Ulstrand/OneDrive/DTU - IT Elektronik/2. Semester/Digitale Systemer/Software/3 ugers/LC3/LC3Zybo/lc3_computer.vhd}
  {C:/Users/Christian Ulstrand/OneDrive/DTU - IT Elektronik/2. Semester/Digitale Systemer/Software/3 ugers/LC3/LC3Zybo/lc3_debug.vhd}
  {C:/Users/Christian Ulstrand/OneDrive/DTU - IT Elektronik/2. Semester/Digitale Systemer/Software/3 ugers/LC3/LC3Zybo/student_code.vhd}
  {C:/Users/Christian Ulstrand/OneDrive/DTU - IT Elektronik/2. Semester/Digitale Systemer/Software/3 ugers/LC3/LC3Zybo/zybovios_wrapper.vhd}
  {C:/Users/Christian Ulstrand/OneDrive/DTU - IT Elektronik/2. Semester/Digitale Systemer/Software/3 ugers/LC3/LC3Zybo/top.vhd}
}
read_edif {{C:/Users/Christian Ulstrand/OneDrive/DTU - IT Elektronik/2. Semester/Digitale Systemer/Software/3 ugers/LC3/LC3Zybo/ZyboVIO_SE.ngc}}
read_edif {{C:/Users/Christian Ulstrand/OneDrive/DTU - IT Elektronik/2. Semester/Digitale Systemer/Software/3 ugers/LC3/LC3Zybo/lc3.ngc}}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Christian Ulstrand/OneDrive/DTU - IT Elektronik/2. Semester/Digitale Systemer/Software/ZyboVIO.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Christian Ulstrand/OneDrive/DTU - IT Elektronik/2. Semester/Digitale Systemer/Software/ZyboVIO.xdc}}]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top LC3Zybo_top -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef LC3Zybo_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file LC3Zybo_top_utilization_synth.rpt -pb LC3Zybo_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
